### ISSUE TITLE
Making Conky window clickable... code suggestion

### ISSUE THREAD

**Issue by ghost** [brndnmtthws/conky#1038]
Hi everyone,

Thank you to all contributors for this kind of useful project. I want to suggest a piece of code to make Conky window clickable (not some part of the window, I mean whole window.) If you interested in you can review my repository, [Clicky](https://github.com/heisenbugh/Clicky).

Thank you again.

**Comment by rubyFeedback** [comment]
Interesting. I think I suggested something similar some time ago; not a full GUI but just 
to respond to on-mouse-button click events, to tie some custom action to it.

The idea I have had was to have some pretty display, but a few useful buttons below.
For example, I have a ruby-gtk application similar to tabble: http://www.rillion.net/tabble/index.html

So my idea was to put this on the lower (bottom) area of the conky "widget", and then click on it
to have that menu interface (from gtk) pop up where I can select applications. Sort of like an
additional "file navigator", similar to e. g. KDE having this on the bottom left area.

Anyway - I have not yet checked clicky; will do, but IF possible I would highly recommend to
somehow try to keep this together, related to conky. Otherwise we just have fork after 
fork after fork and things get very diluted, losing manpower over the years - so I think it
is better to try to perhaps see whether conky could also offer this, optionally. (See how
htop was forked, for example; I understand conky in itself was a fork of torsmo)

**Comment by rubyFeedback** [comment]
Perhaps code from libui could help here? They used a single library.

Conky may not even have to add code support as-is and could
perhaps re-use libui if that is available?

See here:

https://github.com/andlabs/libui

And for ruby examples:

https://github.com/kojix2/LibUI

Unfortunately I don't know C or C++ very well so I don't know how to add support
for this into conky as-is. :(
