### ISSUE TITLE
top displays full command

### ISSUE THREAD

**Issue by rififi** [brndnmtthws/conky#113]
Hi,

Since version 1.10.0-2, the "top" variable in Conky displays full commands names. Before, if Deluge was running for example, I had the deluged process written like "deluged".

Now, I have "/usr/bin/python2 /usr/bin/deluged --port=54566 --config=/home/me/.config/deluge".

I think it's too verbose.

Do you know how to come back to the last format ? Downgrading to 1.9 branch solved the issue.

Sincerely

**Comment by marcpayne** [comment]
I agree that it's too verbose now, although there are cases where it might be useful to see the full command line (e.g. for applications that use multiple processes, or Java-based programs).

Unfortunately, I don't see any way to revert to the old format. I propose having two options: `name` and `name_short`. Alternatively, to avoid changing the behavior of old configs, default to short names and have a `name_long` option (or `name_verbose`).

If I have the time, I will look into how the top feature is implemented and try to add an extra option. No guarantees, though, since I'm more of an interested user than a developer. If I can't handle the task, I'll report back.

**Comment by arclance** [comment]
Don't remove the new full length option I like it. 
I have a way to toggle how much is shown since my whole conky has been in Lua for years.

**Comment by rififi** [comment]
Yes as the work is done, having the possibility to choose between a short and long version is a good idea. However, it changes the old behavior, so a note in the changelog would have been great, and a default option set to name_short, as @marcpayne  suggested, would have been a good idea too.

**Comment by rififi** [comment]
Thanks !
