### ISSUE TITLE
Executable names with spaces are clipped if top_name_verbose = false

### ISSUE THREAD

**Issue by marcpayne** [brndnmtthws/conky#131]
I'm filing this bug against my own commit (06722e4a). In the (hopefully rare) case where an executable name contains spaces, the output of `${top name <num>}` is clipped if `top_name_verbose = false`. Everything after the first space is ignored, and the reason is clear from the commit.

From what I understand so far, the problem of getting the cmdline/executable of a process in Linux is not straightforward. There are several sources of this data: `/proc/<pid>/{cmdline,stat,status,exe}` and probably others. Conky uses `cmdline` and `stat`. Personally, I think this is plenty robust since conky isn't meant to replace top or ps. I'm just throwing this out there in case anyone wants to discuss pros and cons of other approaches.

To fix the current issue and make issue #121 easier to fix, it might be useful to add a `basename` entry in the `process` struct in `top.h` that will contain just the executable name. I hope to get some input on this idea before I try to make it happen.

**Comment by Nooby4Ever** [comment]
Given the current string,  you can use some more advanced parsing (eg split on blank-space and return all groups, with again an added blank-space in between, until a group starts with "/" or "-"). But this will only lower the erroneous cases, it is in essence equally error prone just like the current solution.

I don't see any real downsides on the <code>basename</code> solution and that solution would be preferred (since making #121 easier) over my remark above, but my knowledge on the matter is rather limited so my advice must be take with caution.

**Comment by marcpayne** [comment]
Yeah, I've been thinking about several different ways I could parse it. The most robust way seems to involve combining the information from `cmdline`, `stat`, and `exe`. While doing this will help with some of the edge cases, it makes the code too complex.

I think I'll combine the old behavior with the new. Executable file names from `stat` (old) will go into `basename`, and full command lines from `cmdline` (new) will go into `name`. This is how top from procps-ng handles it. Nice and simple, and it will fix both `${top name ...}` and `${if_running ...}` without breaking the new stuff.

Thanks for the input! It's helpful. My knowledge is limited too. I'm trying hard not to spaghettify the code as I figure things out.

**Comment by Nooby4Ever** [comment]
Something else came to mind, while not directly related to this issue it might be worth considering since you're working on it anyway. -No pressure-

You now have 1 setting <code>top_name_verbose</code> to change the ouput of <code>name</code> for the whole config; an other approach would be to add <code>name_short</code> instead of <code>top_name_verbose</code>. The advantage to this is that the user would be able to use both representations of the process name, if desired, within the same config.

If this would over complicate things you don't have to bother since the original request was to get the same behaviour as in conky 1.9(.1). It just though i would mention it though.

**Comment by marcpayne** [comment]
What you describe with `name_short` is what I really wanted to do at first. It would definitely offer more flexibility. One reason I decided against it was code duplication. There would have to be two separate but nearly identical functions, `print_top_name` and `print_top_name_short`. In retrospect, that probably wouldn't have been a big deal...

I'll keep it in mind, for sure. If there ends up being more demand for it, or people are not happy with `top_name_verbose`, I'll dive right in and get it done. :)
