### ISSUE TITLE
[Bug]: Wrong colors on Wayland ?

### ISSUE THREAD

**Issue by stacyharper** [brndnmtthws/conky#1352]
### What happened?

I think there is a bug with colors with the display-wayland. 

```
conky.config = { 
    out_to_wayland = true, 
    alignment = 'top_right', 
    border_inner_margin = 15, 
    font = 'DejaVu Sans Mono:size=12', 
} 
 
conky.text = [[ 
${color red}red 
${color green}green 
${color yellow}yellow 
${color blue}blue 
${color magenta}magenta 
${color cyan}cyan 
${color black}black 
${color white}white 
]] 
```

Which gives:

![](https://dav.missbanal.net/8558276c-5c75-4b10-9ec5-33015c8f65de.png)

I also noted that ffffff also give this cyan white. So I think the mapping is incorrect

### Version

1.16.1

### Which OS/distro are you seeing the problem on?

Ubuntu

**Comment by brndnmtthws** [comment]
The colour mapping with wayland is some custom code, which might not quite work correctly (yet).

**Comment by bi4k8** [comment]
I can't reproduce this with a Conky built only with Wayland support; there, I see the correct, expected colors.

I *can* reproduce this with a Conky built with support for both Wayland and X11, if `out_to_wayland` and `out_to_x` are both set to "yes". I'll try to see what's going on exactly.

**Comment by bi4k8** [comment]
The problem is that Wayland and X11 don't use the same scheme to denote colors. `get_x11_color` returns a `long`, and does not document how that value is to be interpreted. I had hoped that conky was putting 32-bit RGBA colors into a `long` unconditionally, and under Wayland this is the convention that `colours.cc` and `display-wayland.cc`'s cairo code follow. However, the X11 backend treats this `long` as an X11 "pixel" value, which is [interpreted differently depending on the Visual](https://tronche.com/gui/x/xlib/window/visual-types.html) (which is why we need to pass the `Colormap` to `XParseColor`). As such, a pixel value from one display may not correspond to the same color or be valid at all on a different display. The ncurses backend also seems to have different semantics for the interpretation of color `long`s.

As such, I don't know what we should do when multiple backends are enabled. I think the only truly viable way forward is to replace all `long`s referring to colors by a proper `color` struct with r/g/b/a fields, and convert to backend-specific color formats in each backend. Otherwise, multiple backends will always step on each other's toes when it comes to parsing and representing colors.

I can write a patch that would introduce a backend-independent color representation, but it would be somewhat involved. In the meantime, we could work around this by looking at the `out_to_x`/`out_to_wayland` settings in `get_x11_color`.

**Comment by brndnmtthws** [comment]
I think we just need to refactor this so that the input colours are mapped to the corresponding backend representation as needed for each renderer.

**Comment by bi4k8** [comment]
I'll sketch a patch in the next couple days.

**Comment by bi4k8** [comment]
I've written a patch that's a quick workaround for this bug (#1361), and did some prototyping in another private branch towards a larger refactor that uses a `Colour` type everywhere colors are referenced instead of having a bunch of different parts of code that interpret the same `unsigned long` variables in different ways.
