### ISSUE TITLE
XDG Base Directory

### ISSUE THREAD

**Issue by trans** [brndnmtthws/conky#144]
I installed Conky the other day and noticed the config file is `~/.conkyrc`. I'd like to suggest that the project use the XDG Base Directory standard and place the file in `~/$XDG_CONFIG_HOME/conky/`. It has taken awhile but the standard is finally gaining wide support, and home directories everywhere are finally starting to look sane. :smile:

**Comment by marcpayne** [comment]
Hi @trans, what version of Conky did you install? Since commit 00481ee9a, which is in version 1.10.0, Conky follows the XDG standards. It first tries to read its config from `~/.config/conky/conky.conf`. If that fails, it falls back to the old `~/.conkyrc`.

Thanks for your report though! The XDG standards are really nice, and I enjoy seeing my home directory get cleaner as the years tick by. :)

**Comment by trans** [comment]
Mine was an emerge on Gentoo, so yes, it might have been older version. Thanks!

**Comment by Tucos** [comment]
Just a small nitpick sort of related to this issue: the claim that
> Conky follows the XDG standards

is incorrect. The XDG Basedir spec states that the application should look in `${XDG_CONFIG_HOME:-$HOME/.config}` and then fall back to `$XDG_CONFIG_DIRS`; conky only looks in `$HOME/.config`.

**Comment by marcpayne** [comment]
@Tucos You're absolutely right. Thanks for the correction!
