### ISSUE TITLE
[Bug]: Bars use `own_window_argb_value` for transparency, text doesn't

### ISSUE THREAD

**Issue by muellerjoel** [brndnmtthws/conky#1504]
### What happened?

https://github.com/brndnmtthws/conky/issues/1497

The bars aren't displayed from the cores under wayland

### Version

conky 1.19.1_pre compiled 2023-04-10 for Linux x86_64

### Which OS/distro are you seeing the problem on?

Arch Linux

**Comment by bi4k8** [comment]
I believe this is caused by `own_window_argb_value` being interpreted differently on Wayland vs. X11. Specifically, on X11, this only affects the window background, while on Wayland, this alpha value is used for all non-text drawing (because text uses the `xftalpha` setting).

I think we need to decide once and for all how to handle alpha in Conky: is it separate from colors, or included with them? We conflate ends and means in the current configuration scheme: `own_window_transparent` overrides `own_window_argb_value`, but should really be equivalent to `own_window_argb_value = 0`, except that it actually triggers a different implementation that can work in more X11 configurations. Meanwhile, color parsing does support reading alpha values, except for places where the parsed alpha is overridden by `xftalpha` or `own_window_argb_value`.

A workaround for now is to change `own_window_argb_value` to 255, but that does mean it's not really feasible to share configurations between X11 and Wayland, which isn't good.

**Comment by Caellian** [comment]
#2127 cleans up omission from closing commit.
