### ISSUE TITLE
Using network variables causes conky to crash 

### ISSUE THREAD

**Issue by rbx** [brndnmtthws/conky#175]
I've recently updated two systems from Xubuntu 15.04 to 15.10.
On one of them conky kept working fine as before, while on another it seems to crash immediately after the start.

On the system where it crashes I could narrow it down to several variables which cause it to crash.
These are:
```
downspeedf upspeedf addr upspeedgraph downspeedgraph totalup totaldown
```
Removing these from my config allows conky to run normally.

This must be something in my environment, since on the first machine everything works fine with these variables. But so far I was unable to narrow it down what is causing the crash.

Any ideas what is going wrong?

Conky version is 1.10.0 compiled Wed Jul  1 11:26:33 UTC 2015 for Linux 3.2.0-77-generic x86_64

**Comment by marcpayne** [comment]
Hi @rbx, do you have ipv6 disabled on the machine that is crashing? Your issue might be related to #105, although your conditions seem to be a little different.

If any of your repos carry version 1.10.1, please try that first to see if it resolves your problem. If version 1.10.1 is not available to you, I recommend compiling conky from source. Several crashes and other bugs have been fixed since 1.10.0.

If your issue still exists after trying a more recent version, can you please provide a minimal working config that triggers the crash so I may try to reproduce it?

**Comment by rbx** [comment]
Using 1.10.1 with BUILD_IPV6=OFF (and BUILD_XDBE=ON) indeed eliminated the crashes. On the machine where it crashed ipv6 is not available. 

There's just a little problem with this new version - it doesn't understand these two variables:
```
conky: unknown variable '$wireless_link_qual_perc'
conky: unknown variable '$wireless_link_bar'
```

Is this the consequence of compiling without ipv6?

**Comment by marcpayne** [comment]
To enable the `$wireless` variables, you will have to set `BUILD_WLAN=ON`, since it is off by default. 

Also, it shouldn't be necessary to compile with `BUILD_IPV6=OFF` anymore. Cmake will output a warning if ipv6 is not available on your machine, but it will continue to build (it used to abort).

Hope this helps!

**Comment by rbx** [comment]
With `BUILD_WLAN=ON` now everything works.

Thanks for the awesome tool!
