### ISSUE TITLE
[Documentation, Project Management] Would it be possible to use a short-ish changelog, for more important changes?

### ISSUE THREAD

**Issue by rubyFeedback** [brndnmtthws/conky#1985]
Every once in a while I check back on conky. Today I saw a new release of conky, a few days ago.

I don't know how many other releases have been made in the last half year or so. I even less know
what main changes were made or which features were added anew.

Would it be possible to list the more important changes somewhere? This could be a super-short
changelog, just as a summary (or another name if this feels more appropriate).

Something reasonable like 5-20 short feature mentions per year or so. (If it already exists then
perhaps it can be linked in from the main README; I searched for the term "changelog" and
found no mention. Even if conky makes no use of a changelog, I feel it may be useful for 
oldtimes and newcomers to quickly jump to a single, short-ish file that would be a summary.
Could be a yearly summary too, I have no preferences how - you probably prefer something
simple to maintain, so perhaps a .md file should suffice.)

PS: Bug fixes should probably not be part of that file, but only new-features.md or something
like that. Not that bug fixes are bad, mind you, but I specifically mean new-things that may
get people more interested or excited.

**Comment by brndnmtthws** [comment]
It mostly comes down to the amount of mental energy I have. I have put some work into automating most aspects of the process, but these days I'm overworked, underpaid (i.e., paid nothing and unable to find a decent job), and people demand a lot from me from my various projects, personal commitments, and so on. I know that people expect a lot from open source projects because so many of them are done incredibly well, but my day to day life sucks and I just don't give a shit about computers anymore. I'm just trying to survive and pay rent every month.

Be grateful my friend.

Cheers!
