### ISSUE TITLE
execigraph size not affected by default_graph_height nor default_graph_width

### ISSUE THREAD

**Issue by 2Belette** [brndnmtthws/conky#224]
Hi,
in my conky.config I got 
default_graph_width=180,
default_graph_height=10,
default_bar_width=180,
default_bar_height=10,

I notice that execibar is affected correctly by the values but not execigraph.
Any idea?
Many thanks

**Comment by chepioq** [comment]
I think it's because default_graph_width, default_graph_height, default_bar_width and default_bar_height  are not in conky 1.10, they are replaced by default_bar_size and default_graph_size : 
see here : http://conky.sourceforge.net/config_settings.html

default_bar_size	Specify a default width and height for bars. Example: 'default_bar_size 0 6'. This is particularly useful for execbar and execibar as they do not take size arguments.

default_graph_size	Specify a default width and height for graphs. Example: 'default_graph_size 0 25'. This is particularly useful for execgraph and execigraph as they do not take size arguments

**Comment by benoitne** [comment]
Hi chepioq
Thanks for your reply but I think theses parameters are for conky before 1.10
in 1.10 I confirm that default_graph_size 0 25 is not recognonized and has been replaced by height and width, same thing for the format of parameters where it needs to be in default_bar_width=value

**Comment by chepioq** [comment]
ok benoitne
I think you are right.
There must be an error in the code.

In the man page for conky 1.10 I can see default_graph_height and default_graph_width , default_bar_height and default_bar_width.

And in the man page for conky 1.9 just default_bar_size and default_graph_size.

Sorry for my wrong answer.

**Comment by marcpayne** [comment]
Hello @benoitne, thanks for the report. This issue seems to go back several years, from what I can see in the git history. If anyone is curious, please see [specials.cc:247](https://github.com/brndnmtthws/conky/blob/b38ab1117e5daab79d3642b2cc85f8a5d48c89f4/src/specials.cc#L247).

I'll go ahead and submit a PR later today or tomorrow to correct this.

**Comment by benoitne** [comment]
Thanks for your reply
Don't hesitate to let me know when you PR or when you know it would be available in a new commit as I can test

**Comment by marcpayne** [comment]
I've pushed a commit to my repo which should fix the issue. If you can test it, that would be very helpful. Once verified, I'll submit a PR. Thanks!

**Comment by benoitne** [comment]
I have tried but I got multiple issues:
-color of the graph is not the same as my global configuration
-I got an issue I don't have on the master conky github:

I tried a very simple:
${execigraph 10 echo 10}
conky: missing command argument to execgraph object

or

${execigraph 10 "echo 10"}
conky: reading exec value failed (perhaps it's not the correct format?)
sh: 10: command not found

For the last one it is working perfecfly on the original conky github
I also noticed that if I run the ./conky from the master github directory now I see my graph bigger but it doesn't respect the height (same height if I put a default_graph_height=10 or =100) the second graph on my screenshot
![screenshot_2016-03-14_10-56-56](https://cloud.githubusercontent.com/assets/2325706/13740908/8698ac76-e9d3-11e5-8af6-cc85dbe4782e.png)

**Comment by marcpayne** [comment]
Hmm... I merged upstream master to my local repo several days ago, but I neglected to push those changes to my remote repo. That is why you are seeing those discrepancies. Sorry about that. Everything is up-to-date now, so if you `git pull` and recompile, some of the issues you mentioned should go away.

The command `${execigraph 10 echo 10}` will still fail because `echo 10

**Comment by benoitne** [comment]
just tested and you are right the problem seen before is fixed
regarding the scale of the graph with the default_graph_height option I 
don't see any impact when I change the value?

**Comment by marcpayne** [comment]
My previous comment wasn't finished. It is sometimes unfortunate that the tilde key is right above the tab key...

**Comment by marcpayne** [comment]
> regarding the scale of the graph with the default_graph_height option I
don't see any impact when I change the value?

Hmm, can you please post the line from your `conky.text` that is showing this problem?

**Comment by benoitne** [comment]
I tried a very simple 
${offset 20}${execigraph 5 "echo 10"}
with 
default_graph_width=180,
default_graph_height=100,
or 
default_graph_width=180,
default_graph_height=10,
gives the same result...

**Comment by marcpayne** [comment]
Ah, thank you for clarifying. :) In my comment above that I accidentally submitted before I was finished writing it (oops), I mentioned strange behavior with echo statements like that. When conky sees `"echo n"`, where `n` is an integer, it will set the graph height to `n`, overriding the default.

This weekend after work, I'll see what I can do to fix this. What I have in mind is a bit of a hack, but I think it will do.

As silly as it sounds, you can surround the number with single-quotes to work around this behavior.

```
${execigraph 5 "echo '10'"}
```

**Comment by benoitne** [comment]
thanks for your reply :)
the thing is that in my real conky I need to use something like this 
{execigraph 10 "echo $[$(snmpwalk -v 3 -u xxx -a SHA -A xxx -x AES -X xxx -l authNoPriv A.A.A.A .1.3.6.1.4.1.2021.11.10.0 | cut -f4 -d ' ')}

Yes! I use conky to monitor some remote server through SNMP :)
I tried the ' ' but nothing changes, it is like a issue a scaling of the chart, for me the chart has the right height (I need 10 and by default I got 10) but when I got a value like 5 it is like the graph has the log (-l) option so the graph appears like I got 30...

**Comment by marcpayne** [comment]
Well, it looks like you have a `-l` within your command, so that is indeed giving you a logarithmic scale (I should test this, but I'm quite sure). The `-l` and `-t` options are parsed before anything else, even if they are not at the end.

What I will do is this: if there is a double-quoted command, parse out the command *before* all other parsing. This will fix these strange bugs, and also allow you to specify non-default options after your command if desired.

**Comment by benoitne** [comment]
Thanks marcpayne!
you are right it was -l in my snmpwalk command! you found it :)
I decided to launch the command in a script and execi the script then I 
don't have the issue anymore
many thanks for your help

**Comment by marcpayne** [comment]
@benoitne You're welcome! I've pushed another commit into my graph-size-patch branch that should correct the issues with quoted-commands. Please feel free to give it a try and see if you can run your snmpwalk command as before, without placing it in a script.

I've done a lot of testing on my end. Quoted commands with spaces should work like any other commands now, with or without extra options like height, width, colors, etc.
