### ISSUE TITLE
Text and image alignment issues

### ISSUE THREAD

**Issue by zagortenay333** [brndnmtthws/conky#236]
It would nice if there was a way to position images relative to lines and not pixels. This way, even when line heights change due to font size or type, the images would remain aligned to specific lines.

Right now, it's enough to change the distro to ruin the alignment because the font rendering will be different and will affect the line heights as well.

**Comment by nicolasdanelon** [comment]
:+1: this is really necessary !!

**Comment by greatquux** [comment]
Ooh - that's true. Now I feel like discounting my report completely because I use a PPA that changes font rendering, and I never thought it would change things subtly enough to affect this. (It's https://launchpad.net/~no1wantdthisname/+archive/ubuntu/ppa which applies infinality's modifications for freetype and fontconfig.) 

Of course, it's also important to remember this project is based on conky and positioning relative to lines as opposed to pixels may not be possible with conky (I don't know). It might just have to be part of the documentation or set up in a way that is more easy to modify.

**Comment by plikhari** [comment]
Why would you want to position images relative to lines and not pixels - do you understand how fonts are rendered ???
Each font size refers to the height of that font in pixels. Your image - unless it is the size of the font will be much larger. 
Your issue is a normal issue on an open system such a Linux. Changes happening up-stream may not be taking into account many many things. This issue is not just with fonts it is with everything with developers who may not be mature enough to understand you have 96 dpi and they figure their 72 dpi is the universe.
Do not loose heart ::D - there is a work around.
```
use_xft = true,
xftalpha = 0.8,
font = 'DejaVu Sans:size=12:style=bold',
```
See above the default font size is declared as 12. If the font rendering engine gets updated - all you need to do is change that font size and things will start falling into place.

**Comment by zagortenay333** [comment]
Why would I need to know how fonts are rendered? I only know what the issue is and that's the main point of my post, not to provide a solution.

Not sure what the rest of your comment has to do with this issue.

**Comment by zagortenay333** [comment]
I suppose it would be a lot of work to fix this.

Nothing short of some css-like rendering could solve this. If I draw some box, it would have to be able to resize depending on the font; otherwise, the text would always end up out of alignment..
This makes it impossible to create widgets like the harmattan conky linked above. You can only do floating text

**Comment by syco** [comment]
I couldn't agree more with this request, a solution for me would be to scrap the `-p x,y` and align the top left corner of the image where the next character would be, this should respect `${goto}`, `${offset}`, and `${voffset}`.
This would be enough to align images with lines and make things more portable.

**Comment by syco** [comment]
I pushed some code to fix this here: [https://github.com/brndnmtthws/conky/pull/1055](https://github.com/brndnmtthws/conky/pull/1055)

It's (maybe) a bit of a hack, but it works..

Waiting to know what people think about it..
