### ISSUE TITLE
[Feature] Native Support For CPU Temperatures

### ISSUE THREAD

**Issue by vladipus** [brndnmtthws/conky#272]
I was surprised to see no built-in support for CPU temperatures. The `${platform coretemp.0 temp 1}` solution doesn't even work for me, cause on my system (Ubuntu 16.04 LTS) the platform folder has different hierarchy.

Thanks for your work on this project!

**Comment by Nooby4Ever** [comment]
You can use hwmon and hddtemp. eg. `${hwmon 0 temp 1}` (last digit is the cpu core, see documentation using `man conky` or [the wiki](https://github.com/brndnmtthws/conky/wiki/Configuration-Variables)) and `${hddtemp /dev/sda}`

You have to configure `lm-sesors` and have the `hddtemp deamon` running if you want to get the hdd temp. (see [here](https://help.ubuntu.com/community/SensorInstallHowto) or [ubuntu conky](https://help.ubuntu.com/community/SettingUpConky))

**Comment by vladipus** [comment]
Thank you, I've managed to set up the temperatures with` hwmon` now, but can I be sure this tactic is actually cross-platform on modern linucies? How is it different from `platform` way?

**Comment by plikhari** [comment]
Getting system or cpu temperatures is not really that straight forward on all machines. It is how the hardware is configured [mother board] - see [here](http://superuser.com/questions/157461/temperature-monitoring-on-dell-precision-m4500-under-linux-sensors-detect-doesn?rq=1).
So if platform does not work we can try hwmon or some other way around as you see on that link.
Also - Please close this issue if your issue is resolved - thanks

**Comment by vladipus** [comment]
Closing the issue. Can't really say that the problem is solved however. I think Conky itself should try all available variants for getting the temperature.
