### ISSUE TITLE
Conky on xfce disappearing after login

### ISSUE THREAD

**Issue by Radagast** [brndnmtthws/conky#280]
I'm not really sure if this a conky issue or something else...

 Everything was working correctly until a few days ago, now, conky loads and is displayed during the lightdm phase but when switching to the xfce desktop it disappears. It's still running and if I kill the process and run it manually, all is well. There are no error messages in the console or system logs.

Any ideas?

**Comment by plikhari** [comment]
This is something I notice and also sometimes my window manager also craps conky - I have created a shortcut - keyboard and mouse to launch conky again - and it works fine.
I am on Arch Linux - XFCE+Compiz 0.8 series+Emerald

**Comment by mswanson-me** [comment]
I have experienced this as well. My workaround was to launch Conky from a script rather than directly upon boot. I have a script called "conkystartup.sh" which contains the following lines:
`#!/bin/bash
`
`sleep 10
`
`conky -b &
`
This script is called at startup and the sleep time causes Conky not to run until after the problematic part of the xfce startup. Of course, you may need to play with the sleep time and your conky flags, but give this a shot!
