### ISSUE TITLE
Problem building with Audacious Support.

### ISSUE THREAD

**Issue by quicoju** [brndnmtthws/conky#293]
Hi there, 
I'm trying to build conky from the github sources, and I'm getting an error when enabling support for Audacious. 

```
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:340 (message):
   A required package was not found
Call Stack (most recent call first):
   /usr/share/cmake/Modules/FindPkgConfig.cmake:502 (_pkg_check_modules_internal)
   cmake/ConkyPlatformChecks.cmake:298 (pkg_check_modules)
   CMakeLists.txt:37 (include)`
```

Looking at the `ConkyPlatformChecks.xmake:298` it says that Audacious requires `audclient>=1.4.0`. My installed version of Audacious is 3.7.1 and based on the project [webpage](http://audacious-media-player.org/download), it says that `libaudclient` is now legacy and longer provided with the main package, only separately.

```
pkg_check_modules(NEW_AUDACIOUS audacious>=1.4.0)
if(NEW_AUDACIOUS_FOUND)
    pkg_check_modules(AUDACIOUS REQUIRED audclient>=1.4.0)
    pkg_check_modules(DBUS_GLIB REQUIRED dbus-glib-1)
else(NEW_AUDACIOUS_FOUND)
    pkg_check_modules(AUDACIOUS REQUIRED audacious<1.4.0)
endif(NEW_AUDACIOUS_FOUND)
```

Would it be a good idea to remove the `audclient` dependency for newer versions of Audacious? What would you recommend me to do in this case, do I need to install the legacy library even if it's no longer needed?

Thanks!

**Comment by troxor** [comment]
A lot of headers were deprecated after Audacious 3.5.0, it would be easier to just use ${execi N audtool ...} for Audacious info in Conky if you're running a later version.

**Comment by troxor** [comment]
@brndnmtthws would you prefer a patch to rename this module LEGACY_AUDACIOUS or just leave it as is? Currently the pkg_check_modules verifies NEW_AUDACIOUS >= the ancient 1.4.0. In general, how would you like to handle modules whose functionality has been superceded?

**Comment by lasers** [comment]
Okay... This issue is specifically about building with audacious support.

I see I can't compile audacious with this...
```
cmake -DBUILD_AUDACIOUS=ON ../
```

I see I can compile audacious with this...
```
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_AUDACIOUS=ON ../
```

I had no problem compiling with audacious support here (Arch Linux) and on [Docker](https://github.com/brndnmtthws/conky/blob/master/Dockerfile) too.

The website says...
>libaudclient is a legacy D-Bus client library that used to be included with Audacious. Though it is no longer actively maintained, libaudclient still works with the current version of Audacious and can be downloaded separately.

Legacy, but still works with the current version of Audacious.

>Would it be a good idea to remove the audclient dependency for newer versions of Audacious? What would you recommend me to do in this case, do I need to install the legacy library even if it's no longer needed?

Probably a good idea to remove `audacious` support from conky in favor of `mpris` support. Maybe other music players could go too. Since this is still working, I think it is better to leave this alone and wait for it to actually die first.

You still can use `${exec audtool current-song}` and many others.

>do I need to install the legacy library even if it's no longer needed?

Only if you still want to use builtin audacious variables.

-----

Note: Top is conky built-in audacious variables. Bottom is audtool variables.

![2018-08-15-173323_779x855_scrot](https://user-images.githubusercontent.com/852504/44218305-0beea180-a13f-11e8-8b09-feb73a489700.png)

Also, 2 years 2 months passed. I'm just going to close this. I hope this helps a lot. Thank you.
