### ISSUE TITLE
return value of malloc() not checked against NULL

### ISSUE THREAD

**Issue by ThomasSteudten** [brndnmtthws/conky#301]
Hello

Found some places in conky source code, where the return value of malloc() isn't verified, but used.

Thomas

**Comment by bokailya** [comment]
By default, Linux follows an optimistic memory allocation strategy. This means that when malloc() returns non-NULL there is no guarantee that the memory really is available. In case it turns out that the system is out of memory, one or more processes will be killed by the OOM killer.
 -- man malloc 
I think it does not have big sense

**Comment by ThomasSteudten** [comment]
This is the behavior of the kernel, to kill processes when "out-of-memory (OOM)". But conky runs in the userland, and it's a good programming style to check the return value of a system- or library-call. Using a NULL-Pointer as it is a valid pointer to a memory location, keeps trouble - and much more in a multi-threaded application. // But, sure it's up to you..

**Comment by bokailya** [comment]
Hm.. I think you right.
