### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SethDusek** [brndnmtthws/conky#305]
Where can I get proper documentation of conky > 1.10? All of the conkyrc configurations on the wiki use the old format, plus the documentation in general is pretty bad

**Comment by Nooby4Ever** [comment]
The wiki on github is rather up-to-date with >1.10: [Config Settings](https://github.com/brndnmtthws/conky/wiki/Configuration-Settings), [Config Variables](https://github.com/brndnmtthws/conky/wiki/Configuration-Variables),  [Wiki](https://github.com/brndnmtthws/conky/wiki) (the example configs are indeed outdated) but since the wiki not updated for every minor release it may be slightly outdated. You can always use the command `man conky` or look for the html documentation pages, if available, on your computer to get the correct documentation for your version. But i would agree, the documentation is rather limited and there is no tutorial available. You can always help to expand/improve the wiki. You might also update the manual (man pages), eg in the style of: [Casey's Conky Ref (Conky 1.9)](http://www.ifxgroup.net/conky.htm)(many people new to conky seem to find this helpful), you can find the documentation here: [/doc](https://github.com/brndnmtthws/conky/tree/master/doc)

I assumed you meant config documentation, general code documentation is not available. There are only some coder comments.

**Comment by SethDusek** [comment]
@Nooby4Ever Yeah but atleast as far as I can tell there's no step-by-step guide of writing a config file for conky. I read a bit of the lua guide and the grammar was pretty bad and there was no syntax highlighting for the lua portions. I tried fixing some of it up but I wasn't able to fix all of the mistakes

**Comment by Nooby4Ever** [comment]
I know i have "ported" the lua tutorial to the wiki myself; alas the original author did not do a proper write up and used next to none punctuation (in his defence he stated it wasn't really meant to be a proper tutorial, just a quick write-up). The content of the tutorial is fine (imo, and if you're new it is better than figuring everything out for yourself) but i agree the grammar is pretty awful. Unfortunately i did/do not have time, now and in the near future, to make a new lua tutorial (and nobody else seems to do it). There is lots of (lua) knowledge/tutorials on this blog: [The Peachy Blog](http://thepeachyblog.blogspot.be/p/index-or-home-page.html) which should be updated/ported to the wiki too, since that blog is abandoned and may go off-line at any time. Unfortunately writing tutorials is a labour intensive task which takes a lot a time (and the conky community is rather small).

As for a step-by-step conky guide, there is indeed none like i said. Until someone takes the time to write one this won't change, you can google around and some older tutorials might pop-up but they are outdated but should be roughly paint the picture. But for people new to conky these will probably be unappealing , too confusing and frustrating to really use. At the moment conky is kinda "learn by example + documentation".

But i agree this is an issue, certainly for new people, but i doubt it will change any time soon.

**Comment by SethDusek** [comment]
@Nooby4Ever Ok, I understand. However, I took the time to read somebody else's conkyrc and convert it to lua syntax, and am trying to modify it into a "Now playing' kind of widget that uses mpris, however the ${lua playing} thing is returning nothing, and it's just displaying "Now playing: " Here's the script https://gist.github.com/590cd70ba8d38fa86f84378254958fb0

**Comment by plikhari** [comment]
@SethDusek  this is a gradual transition and a learning curve. With example code one learns faster - but more so - the desire to learn. You are on the correct track :-)

Conky is like an open platform - you have not just the variables - but - with Lua as an addon language. Lua in itself is just that - a language script - but - with the graphics cairo library integration - it is magic!!! - a chance to impress the world.

Not to mention the magic @Nooby4Ever has done - follow those steps and you are on !!!

**Comment by lasers** [comment]
Almost two years later... I hope the documentations are reasonably acceptable now. Thanks.
