### ISSUE TITLE
Shortcut makes conky widget disappear!!

### ISSUE THREAD

**Issue by BeyondLimitation** [brndnmtthws/conky#310]
<code>conky 1.10.1 compiled Wed Jan  6 17:11:44 UTC 2016 for Linux 3.19.0-43-generic x86_64
Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky

 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * Curl
  * RSS
  * Weather (METAR)
  * Weather (XOAP)
  * wireless
  * support for IBM/Lenovo notebooks
  * nvidia
  * eve-online
  * builtin default configuration
  * old configuration syntax
  * Imlib2
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support

 Lua bindings:
  * Cairo
  * Imlib2
  * RSVG
 X11:
  * Xdamage extension
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * Audacious
  * MPD
  * MOC
  * XMMS2

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256
</code>

My System:
Ubuntu Linux 16.04.1 LTS
4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

My Issue:

When i press **Alt+Tab** and go to desktop, my widget has been disappeared!!
I can't figure out how to solve this problem..

Any suggestion??

**Comment by plikhari** [comment]
Have you considered using other window_type - you have normal, desktop, dock, panel or override - Try normal or override and see how it goes.

**Comment by ACinnamonUserInUK** [comment]
I find, on conky 1.10.3~1 (from my distribution's repositories), that:

- setting `own_window_type` to `desktop` or `dock` is the only way to stop 'show desktop' hiding conky
- setting `own_window_type` to `normal` is the only way to get conky to exclude icons from the area that conky occupies.

Since I want both those things - conky melded with the desktop, and conky to exclude icons, I am a bit unhappy! Perhaps I should get the latest version of conky from here; perhaps that will give me what I want.

**Comment by BeyondLimitation** [comment]
@plikhari @ACinnamonUserInUK 
I solved the problem. I don't the specific reason, but found the solution.

Conky version 1.10 or higher uses new syntaxs, so i converted them.
And last step is` own_window_type` must be located between `own_window_transparent` and `own_window_hints`!

Then ta da! I solved it!
It works what i desire!! Yay!

**Comment by ACinnamonUserInUK** [comment]
@BeyondLimitation:

Please clarify. Are you saying the following?

If, in Conky >=1.10, one wants to use `own_window_type = desktop` but also at the same time have Conky exclude icons, then `own_window_type` must be located somewhere (anywhere) between 'own_window_transparent' and 'own_window_hints'.

Well,  I didn't have 'own_window_transparent' in my Conky, but I did have `own_window_argb_visual`, so I added 'own_window_transparent' in the position you suggested (and put `own_window_argb_visual` next to it) and . . it doesn't work. That is: icons can still be moved over the Conky.

**Comment by plikhari** [comment]
@ACinnamonUserInUK 
look at this then - these are comments and information I give in my config files for my users to figure it out.
As you notice i do not use real transparency!!! Real transparency does not work well with `override` - which is what I need to get what you are looking for.  This works on Arch XFCE4 + Compiz 0.8.4
```
	own_window = true,
-------------------------------------------------------------
-- change this if you are not getting any conky display
-- options are: normal, desktop, dock, panel or override (default: normal)
-------------------------------------------------------------
	own_window_type = 'override',

-------------------------------------------------------------
-- uncomment below hints line if not using override
-------------------------------------------------------------
-- own_window_hints below,sticky,undecorated,skip_taskbar,skip_pager

	own_window_transparent = true,
	own_window_class = 'Conky',

-- ARGB can be used for real transparency,
-- note that a composite manager is required for real transparency
-- own_window_argb_visual yes

-- Set the transparency alpha value from 0 to 255
-- own_window_argb_value 100

```

**Comment by ACinnamonUserInUK** [comment]
@BeyondLimitation 

Well, thank for that. However: (1) I suspect we are not even trying to solve the same problem (see my previous post); (2) the config you have posted seems to contradict your own advice about the placing of `own_window_type`. Also (3) I believe that `own_window_class = 'Conky',` is redundant, because 'Conky' is the default value anyway.

I am on Mint Cinnamon, which has 'Mutter (Muffin)' as its window manager. On that setup, setting the window type to 'override' seems - whatever else I do - to make the Conky invisible.
