### ISSUE TITLE
NOAA weather data service discontinued

### ISSUE THREAD

**Issue by frisbee00** [brndnmtthws/conky#313]
Conky has stopped showing weather information from http://weather.noaa.gov.
The service appears to be discontinued.

**Info**:
- http://weather.noaa.gov/pub/data/observations/metar/stations/
- http://www.nws.noaa.gov/om/notification/scn16-16wngccb.htm

**Comment by Nooby4Ever** [comment]
Yes the weather "module" could use an update/overhaul. Related [issue](https://github.com/brndnmtthws/conky/issues/65). At the moment many people use alternative conky script(s): [TeoBigusGeekus @ Bunsenlabs](https://forums.bunsenlabs.org/viewtopic.php?id=189). (which are very powerful btw). They could be build into conky itself... but somebody need to gets their hands dirty.

**Comment by plikhari** [comment]
OK now we are talking - I am the author of conkywx - [a conky weather program](http://foreverquest.blogspot.com/).

Well Teo uses one implementation - conkywx uses another - has animations and more - get surprised :-)

**Comment by Nooby4Ever** [comment]
Oooh nice, took a quick look  at the code; that's some serious conky! (sorry for not mentioning your script, i don't really know what is available these days).  Since you've made it; do you reckon it would be useful to add something similar to conky or is it too specialized/detailed (would have no icons, no translations, no lua scripts, ... those would be part of the skin and not conky itself of course) and better done with an external script (eg. yours or Teo's)? Or conky could provide some more basic weather info like it did/does and users which desire more detailed information could use an external script.

(correct me if i'm wrong, i don't use any weather info in my conky configs so i'm completely out of my comfort zone here)

**Comment by plikhari** [comment]
Thank you @Nooby4Ever :-)
I do have some ideas which perhaps can help. At present neither of the access points are working. 

One way is hard wiring the URL - the way it is at present - but more flexible way would be to have an option to read off a text/data file. For instance for METAR you need the METAR string or line - same is the case with other weather feeds.

In place of weather.com [which is also not working] - wunderground.com will be a better choice - it was bought out by weather.com some time back. They have a developer licence which is free - you get XML or JSON feed - which can be parsed by conky.

Another resource is mentioned here #65 - they offer free API Key for open source projects - you have seen this.

METAR is also good - but the site has been removed - alternate resource is **aviationweather.gov** - this is the link for the data feed - there is a proper form which helps you in setting the correct URL to use.
```
http://www.aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=csv&hoursBeforeNow=1&mostRecent=true&fields=raw_text,metar_type&stationString=ICAOID
```

conkywx actually generates all information that is not an observation - such as Astronomy, feel good / apparent temp, graph trends for weather elements etc. Current weather information is picked from one or more sites - depending your chosen option - while the forecast data can come from another - since METAR does not have forecasts. Then there is consolidated Earth Quake activity from USGS and the European portal and other features.

So for integration - I feel we need to focus to keep conky trim and sleek like it is and perhaps modify the current weather implementation as stated above.

cheers

**Comment by Nooby4Ever** [comment]
I've taken a look on how [Rainmeter](https://forum.rainmeter.net/viewtopic.php?f=13&t=23289) (our more fleshed out windows counterpart) handles things, they use: ```http://wxdata.weather.com/weather/local/SWXX0004?cc=m&unit=c&dayf=3``` which returns a nice xml page.
```
<dayf>
        <lsup>8/28/16 7:00 AM CEST</lsup>
        <day d="0" t="Sunday" dt="Aug 28">
        <hi>63</hi>
        <low>54</low>
        <sunr>5:42 AM</sunr>
        <suns>8:06 PM</suns>
        
        <part p="d">
          <icon>12</icon>
          <t>Rain</t>
          <wind>
      <s>10</s>
      <gust>N/A</gust>
      <d>98</d>
      <t>E</t>
    </wind>
          <bt>Rain</bt>
          <ppcp>90</ppcp>
          <hmid>70</hmid>
        </part>
        <part p="n">
          <icon>12</icon>
          <t>Rain</t>
          <wind>
      <s>10</s>
      <gust>N/A</gust>
      <d>98</d>
      <t>E</t>
    </wind>
          <bt>Rain</bt>
          <ppcp>100</ppcp>
          <hmid>91</hmid>
        </part>
      </day>
```
It is surprisingly detailed (imo). For their API access they refer to wunderground.com (no surprise if they bought it) but it seems you can just call it anyway (without token, you probably have way less API options i assume or less up -to-date data)? So pretty similar to openweathermap.org. Getting a (free) account for an API key is not our call but brndnmtthws, and puts more work on the maintenance (they might refresh keys, ect...). I don't know if wunderground.com has a special account for open source projects but their developer account only allows 500 calls/day; that's not enough for all conky users. So if possible i would, personally, try to avoid relying on an API key.

The METAR variant is appealing from the developer point of view since it is a fixed format, so once implemented no need to change the code ever again. Only the source from where to get it. As far as a quick look it seems like it needs a lot of "translation" (descriptor to real name:, eg. DZ -> Dizzle) which makes the code long and heavy and is not required if you use wxdata.weather.com for example. So probably a bit too much for conky? (since i agree with you keeping it trim and sleek is the main focus here, for fancy stuff you can use custom scripts; like yours ;) )

At the moment it seems to me wxdata.weather.com is our best bet, since the xml parsing is already present within conky and there is no need for translations or an API key. It even has icon support (although providing the images is not conkys responsibility). But correct me if i'm wrong or looking over things. (the downside of course is they might quit this service tomorrow (so to speak) and we would be back to the drawing board.)

**Comment by plikhari** [comment]
Hey lol :D - I also use the same URL for weather.com [ ok slightly different options ]- but it is not supported and nor documented - it is legacy URL which is still coming through. Many times it may not match the forecast or current weather from wunderground.

METAR parsing is already built into conky !!! - have a look at weather.cc file. I use my own parser in C.

wunderground API key will be different for each user - so the conky developer will use his/her and the user will use his/her in the line input.

The other option was using that openweather thing - well - they would give a single permanent API key - which would then be hard wired into conky for all to use.

And boss - 500 calls a day is more than enough - weather does not change that fast even in a hurricane - that is over 20 calls per hour.  I absolutely make it clear to all and sundry - not more than 4 calls per hour - preferably only 2 or less. Most METAR stations update every hour duh lol - current conky docs show default time interval is 30 minutes [minimum].

I have animated anemometer and windwane so one gets the feel of real time data - even when it is not ;-) - The websites use java-script - I use Lua - wicked :p - I know lol

**Comment by Nooby4Ever** [comment]
It seems like my edits were too late; and for the 500/day i thought it would be a global API key (for all conky users). 

> I have animated anemometer and windwane so one gets the **feel of real time data** - even when it is not ;-) - The websites use java-script - I use Lua - wicked :p - I know lol

Lol, i immediately thought "you could control a real fan with that data and let it rotate and blow at the current wind  speed to simulate the wind outside" :p

But [problem](https://www.wunderground.com/weather/api/d/docs) for wunderground.com: 
> 4) Per the Terms of Service the Weather Underground logo must be included with a credit line where Weather Underground data is displayed. Please see individual Logo variations for all acceptable combinations of layout in the Logo Usage Guide.

I did not read the whole TOS but this is already a deal-breaker and since when you sign-up you agree tot he TOS... Didn't read openweathermap's TOS but a first quick look does not reveal any "deal-breakers". To be honest we could just let the conky users sign up to openweathermap themselves, they have a [free account](http://openweathermap.org/price) as well. Conky skins like [Conky-Vision](https://github.com/zagortenay333/conky-Vision)(neat config) and [Conky-Gnow](http://hernanarce.deviantart.com/art/Conky-Gnow-multilang-505074617) already implemented this themselves.

***

I currently don't have the time to update the weather module in conky myself (if no one else does it i will eventually but i can take a while) but it seems like openweathermap (users sign up; less maintenance for conky) and aviationweather.gov for METAR seems the way to go. On the other hand.. we could just drop the METAR support all together since i doubt many people will use it if they can use openweathermap (+ a smaller code base for conky) . (<- correct me if i'm wrong) External scripts like yours make it available anyway for those that, explicitly, do want to have that data.

So for for example (mock-up):
```
conky.config = {

-- Weather (openweathermap)
weather_apiKey= 'XXXXXXXXXXXXXX', -- from user account
weather_cityId = 'XXXX',
weather_units = 'metric',
weather_interval = 120, -- in minutes, minimum 60/120? (site states updates every "<2 hours")
... ect all api options

weather_iconFolder = './icons/*.png/jpg/svg/...', -- provided by the user (images must have correct file names)
}

conky.text=[[ 
${weather day1 tempLow} - ${weather day1 tempHigh}
${weatherIcon day1 [other options that are available for images, see $image. eg size]}
]]
```

(just giving my thoughts on the matter, other options are possible too of course)

**Comment by plikhari** [comment]
Yeah I saw your comments after I has sent in my reply - but then life got in the way ;-)

Yes I just included METAR as it gives a very reliable system for weather besides what the commercial systems give - and quite frankly they all use METAR as well. One could use METAR for current info and openweather for forecast or as one feels comfortable - we do agree a user's Desktop is a very personal thing lol. We hedge for current weather and a 10 day forecast and see what openweather offers.

Openweather would give a global key - so we do not need to ask for a user key - rest looks fantastic.

If you want I can start a dialog with openweather for an API key for conky. 

I feel 30 minutes update minimum is good.

**Comment by Nooby4Ever** [comment]
> Yes I just included METAR as it gives a very reliable system for weather besides what the commercial systems give - and quite frankly they all use METAR as well. One could use METAR for current info and openweather for forecast or as one feels comfortable - we do agree a user's Desktop is a very personal thing lol. We hedge for current weather and a 10 day forecast and see what openweather offers.

Ok fair enough, code is already available anyway.

> Openweather would give a global key - so we do not need to ask for a user key - rest looks fantastic.
> If you want I can start a dialog with openweather for an API key for conky. 

That's not my call to make, i'm not the maintainer. I assume openweather will not just give a key but will require to register a "conky" account as well. -> you've got to contact @brndnmtthws first, since it's "more" work for him (and he would need to have the account details thus it probably must be registered on his email address; in case the password gets lost). If they just give a key you can go for it.

>  I feel 30 minutes update minimum is good

That makes sense for METAR data indeed.

**Comment by plikhari** [comment]
Yes I agree with all points - lets see what happens ... He should get a copy of the message since he was mentioned here again @brndnmtthws  ?? I do not have his contact details ...

**Comment by lumper5** [comment]
In the meantime, this is a quick and easy workaround: https://bbs.archlinux.org/viewtopic.php?id=37381

**Comment by krakenfury** [comment]
The METAR is available from NOAA here: http://tgftp.nws.noaa.gov/data/observations/metar/
Would like to try changing the hardwired URI, but couldn't find it.  @plikhari where is this set in the code?

**Comment by krakenfury** [comment]
Nevermind.  It's right weather.cc
Changing the uri works fine for me.  Going to put in a pull request.
Will need to update the documentation, as well, but [Conky Objects](http://conky.sourceforge.net/variables.html) is still hosted at sourceforge.net.  Will there need to be a seperate request to get that changed?

**Comment by krakenfury** [comment]
PR here: https://github.com/brndnmtthws/conky/pull/325
Please review.
