### ISSUE TITLE
about $if_match, always excute else

### ISSUE THREAD

**Issue by zosy** [brndnmtthws/conky#351]
conky -v
conky 1.10.4

issue:
$if_match result >0  allways excute else section ${exec gnome-terminal}

my .conkyrc

conky.config = {
    alignment = 'top_left',
    background = false,
    border_width = 0,
    cpu_avg_samples = 2,
	default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    use_xft = true,
    font = 'DejaVu Sans Mono:size=12',
    gap_x = 3645,
    gap_y = 5,
    minimum_height = 5,
	minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_stderr = false,
    extra_newline = false,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_argb_visual = true,
    own_window_argb_value = 150,
    own_window_transparent = false ,
    stippled_borders = 0,
    update_interval = 3.0,
    uppercase = false,
    use_spacer = 'none',
    show_graph_scale = false,
    show_graph_range = false
}
conky.text = [[
#green
#red
#white
${if_match ${execi 2000 ps -ef | grep sshd | grep -v grep | wc -l}>0}\
${color green}[running]\
${else}\
${exec gnome-terminal}${color red}inactive!\
${endif}
]]

**Comment by dbriba** [comment]
I think it is because ${else} don't work with ${if_match}
${else} work only with a simple ${if}

$[if_match}
description:
Evaluates the given boolean expression, printing everything between $if_match and the matching $endif depending on whether the evaluation returns true or not. Valid expressions consist of a left side, an operator and a right side. Left and right sides are being parsed for contained text objects before evaluation. Recognised left and right side types are:
double - Argument consists of only digits and a single dot.
long - Argument consists of only digits.
string - Argument is enclosed in quotation marks (")
Valid operands are: '>', '<', '>=', '<=', '==', '!='.

**Comment by zosy** [comment]
@dbriba  I've got it, thanks for reply.
