### ISSUE TITLE
Feature request: personal news ticker for Conky

### ISSUE THREAD

**Issue by linuxscripts** [brndnmtthws/conky#353]
I wanted to request a feature which I think would be very valuable.
This feature would be a news ticker for Conky, which only shows the news items people are interested in (hence excluding news topics that appear in the news a lot -even of those agencies they subscribed to- but which they don't want to know anything about). One possible way to do this is by having each posted news headline be given a category, and members that subscribed to a channel can then set their preferences to not include certain categories.  

Depending on how the RSS is made up, I also think that the news headlines can be linked, so if people want to know more about a certain news headline they can get the full story. I think that last feature could also persuade smaller news agencies to include it, as they can for instance restrict access to the full news article (make it available only for paying members) but still provide the news ticker RSS itself as FOSS. Perhaps that, besides RSS (provided by any news agency the user wishes to follow), twitter feeds (again of any twitter account) could also be used.

I got this idea as an extension to the ideas I all ready had for my custom Conky package for Slitaz (which is still unfinished btw). See https://sourceforge.net/projects/taz/files/semi_ready_packages/
or visit the trixarian forum (Tazpkg DevCom) where I posted this idea as well.

**Comment by plikhari** [comment]
I wanted to respond earlier - since I had already implemented this in [conkywx SIX](http://foreverquest.blogspot.com). Now that the program is released we can discuss the issue.

First off - conky offers a framework which can be extended with lua
A game changing improvement in conky would be mouse integration within conky core.

> This feature would be a news ticker for Conky, which only shows the news items people are interested in (hence excluding news topics that appear in the news a lot -even of those agencies they subscribed to- but which they don't want to know anything about). One possible way to do this is by having each posted news headline be given a category, and members that subscribed to a channel can then set their preferences to not include certain categories.

One could use key words to match - sort of category and topics and description can be displayed.

> Depending on how the RSS is made up, I also think that the news headlines can be linked, so if people want to know more about a certain news headline they can get the full story.

conky does not have mouse integration - so this is not happening

**Comment by linuxscripts** [comment]
Hi plikhari,
perhaps you can mail me at my e-mailaddress (linuxscripts@gmx.com) so we can discuss this further.
I looked at your github profile and you seem not to have any repositories yet. So I guess the best way forward would be to first post the Conkywx repo via your github account. After that, you could optionally make a conky package for slitaz of the conkywx binary, and perhaps integrate the other things I proposed for conky as well (see the semi_ready_packages).

**Comment by mswanson-me** [comment]
It sounds like you are describing a separate service for weighting news articles per user and creating a custom RSS feed based on that. Any RSS feed can be displayed by Conky using the ${ rss } tag. The method by which the RSS feed is compiled is irrelevant. 

Since this is outside the scope of Conky, this issue is being closed.
