### ISSUE TITLE
Month name problem with UTF-8 and LANG=de_DE (while month March only)

### ISSUE THREAD

**Issue by bymoz089** [brndnmtthws/conky#377]
Following config for date string:
${time %a %d.%b %Y}

 gives a strange output with environment var LANG set to:
LANG="de_DE.UTF-8"

Screenshot:
![lang-de_month-problem-march](https://cloud.githubusercontent.com/assets/15787117/23793870/b83e4c14-058d-11e7-9443-c2ab97e0b437.jpg)

it should state:
Fr 10.Mär.2017
(end of the year string from 2017 is cut because of window dimensions, but this is not the problem)

**Comment by AlexeyBond** [comment]
Looks like march is the only one month name of which in german language contains a character represented by more than one byte in UTF-8. So probably the problem is that conky with your configuration is not able to display any character behind first 127.

If you keep see strange characters when just put a plain text "Fr 10.Mär.2017" or "Frühling In Paris"(I have no idea what it means) in config then try the following:

- enable UTF-8 mode:
    `override_utf8_locale = true`
- enable xft fonts and set custom font:
    ```
    use_xft = true,
    font = 'DejaVu Sans Mono:size=7' -- or any other font
    ```

**Comment by plikhari** [comment]
@bymoz089 

If you issue is resolved - can you perhaps close this issue - thanks

**Comment by Shura0** [comment]
I have similar issue with Russian.

Config contains the lines
> override_utf8_locale = true
> use_xft = true,
> font = 'Bitstream vera sans mono:size=10

But it does not help.
OS is FreeBSD.

**Comment by bymoz089** [comment]
Thank you for helping. `override_utf8_locale = true` fixes the Umlauts display issue, they are displayed now.

But for every Umlaut conky thinks the displayed string is longer than it actually is and cuts off the string, leaving empty space at the end. I will file a new bug, explaining this
