### ISSUE TITLE
Conky does not want to be compiled by default lua

### ISSUE THREAD

**Issue by ghost** [brndnmtthws/conky#395]
Hi.

I am trying a .zip checkout from github repo, at 29th may 2017:

I am using this command:

    cmake -DCMAKE_INSTALL_PREFIX=/usr .

The result is:

-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/libX11.so
-- Checking for one of the modules 'lua>=5.3;lua5.3;lua-5.3;lua53;lua5.2;lua-5.2;lua52;lua5.1;lua-5.1;lua51;lua>=5.1'
CMake Error at /Programs/Cmake/3.8.1/share/cmake-3.8/Modules/FindPkgConfig.cmake:641 (message):
  None of the required
  'lua>=5.3;lua5.3;lua-5.3;lua53;lua5.2;lua-5.2;lua52;lua5.1;lua-5.1;lua51;lua>=5.1'
  found
Call Stack (most recent call first):
  cmake/ConkyPlatformChecks.cmake:267 (pkg_search_module)
  CMakeLists.txt:37 (include)

-- Looking for XineramaQueryScreens in /usr/lib/libXinerama.so
-- Looking for XineramaQueryScreens in /usr/lib/libXinerama.so - found
-- Configuring incomplete, errors occurred!
See also "/Depot/jj/conky-29.05.2017/CMakeFiles/CMakeOutput.log".
See also "/Depot/jj/conky-29.05.2017/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.

Conky fail to be compiled.

Lua is available though on my system:

> Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio

If I understand the situation then I have to install some lua addon. Ok.

https://github.com/antonio-malcolm/conky-configs/wiki/How-To-Compile-Conky-And-Its-Lua-Bindings-

I'll give it a try lateron.

I have a suggestion meanwhile. Could the error message be more explicit and also notify the user that he has to install these add-ons please?

**Comment by plikhari** [comment]
> -- Checking for one of the modules 'lua>=5.3;lua5.3;lua-5.3;lua53;lua5.2;lua-5.2;lua52;lua5.1;lua-5.1;lua51;lua>=5.1'
CMake Error at /Programs/Cmake/3.8.1/share/cmake-3.8/Modules/FindPkgConfig.cmake:641 (message):
None of the required
'lua>=5.3;lua5.3;lua-5.3;lua53;lua5.2;lua-5.2;lua52;lua5.1;lua-5.1;lua51;lua>=5.1'
found

conky requires lua 5.1 - you will probably get lua 5.1.5 - which is also fine.

refer to issue #394

**Comment by lasers** [comment]
Missing `lua51` triggered this problem. Solution provided, thanks! @ghost ghosted. Closing.

**Comment by GHPS** [comment]
P.S., just for the record: I was trying to install
the latest version of conky (version 1.11.5_pre)
on Kubuntu 18.04 and ran into the same error
messages (lua5.3, libcurl4 and libimlib2 
installed but not found).

After following various paths that led to
nothing (installing lua5.1, lua5.2, libtolua, ccmake 
and specifying directories in cmake like
LUA_LIBRARY, LUA_INCLUDE_DIR, PACKAGE_LIBRARY_DIR)
I finally solved the problem which was caused
by pkg_config: In Kubuntu the paths for
pkg_config differ from what cmake expects
by default. Thesefore it's necessary to
specify these in advance:

`export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig"`

after that cmake works without further ado 
using lua5.3, liblua5.3-dev (no need to install libtolua-dev)

`cmake -DBUILD_LUA_CAIRO=ON  .. `

if you wish to use Cairo (which makes sense).

Since everyone on the Debian/(K)Ubuntu platform will
face this issue when building conky, it might be a good idea
 to include this information in the wiki[1].

1: https://github.com/brndnmtthws/conky/wiki/Installation
