### ISSUE TITLE
Font's Don't Change/Render Correct In 1.9.0 

### ISSUE THREAD

**Issue by ghost** [brndnmtthws/conky#43]
I use Slackware64 and in 14.0 Conky 1.9.0 worked great. I just recently did a fresh install to upgrade to 14.1 and now Conky does not render the fonts correct, meaning if it's a LIGHT font it still appears as bold, I don't know why they always appear now bold...

Slackware 14.1 uses xorg-server-1.14.3

Here's the config I'm playing with you can download at Dropbox;

https://www.dropbox.com/s/5g05bgafmo48ph9/conkyrc-stats.dk.zegoe

In the config you'll notice the font 'Aller Light' which should appear as a 'Thin looking font', however if I wanted a more thick/bold looking font then I'd write it as 'Aller', but even though I'm using it as 'Aller Light' the output appears as Aller on the desktop, bold...

I've tried using several font names and they all appear now bold too...

Thanks...

**Comment by mswanson-me** [comment]
Is this issue still outstanding in the current version of Conky? If so, please update this issue. Otherwise, the issue will be closed in 2 weeks.

**Comment by lasers** [comment]
4 years, 6 months passed. He ghosted. This bug is marked invalid due to wrong font usages. He wanted `Aller`, `Aller:bold` (or) `Aller Light`, `Aller Light:bold`.... not `Aller`, `Aller Light`.

![aller](https://user-images.githubusercontent.com/852504/43672509-0238c158-9775-11e8-8594-3cdcaa84d2fd.png)
