### ISSUE TITLE
Hey I am using xfce genmon plugin to run command "conky -i 1" every second. This does not update the ${downspeedf} variable and it displays 0 always

### ISSUE THREAD

**Issue by gps08** [brndnmtthws/conky#472]
https://bbs.archlinux.org/viewtopic.php?id=168321
same problem is described here

**Comment by lasers** [comment]
I don't believe this is a bug because some variables/objects requires `conky` to be running at all times for the numbers to be printed correctly... perhaps to calculate differences between intervals or to accumulate values over intervals. This is one of them.
```
    -i COUNT
        Number of times to update Conky (and quit).
```
Compare `conky -i 1` and `conky -i 10`. You'll see it's working okay. The first interval is always `0.0`.
