### ISSUE TITLE
Conflict with qBittorrent

### ISSUE THREAD

**Issue by Trendle** [brndnmtthws/conky#476]
Conky becomes very slow (almost to the point of freezing) when I run qBittorrent. Is there a way to fix that?

**Comment by lasers** [comment]
I'm closing this due to lack of information.

If you're still experiencing this, please reopen with more information. We'll be wanting your config and steps to trigger this behavior. If you know `conky` will crash, run it under `gdb` (eg `gdb conky`) until the crash occurred. From there, type `bt full`. That's the log they want... then we'll find out if it's fixable. Thanks.  If nothing happened, then I'm not sure. It might be related to variables or something else.
