### ISSUE TITLE
draw_outline turns shades on too

### ISSUE THREAD

**Issue by Oreolek** [brndnmtthws/conky#706]
Whenever I set `draw_outline` to true, conky also turns shades on.
Noticed on 1.10, checked on 1.11.1 (default cmake).

**Comment by lasers** [comment]
My findings First thing first, I grep the settings. It's so old.
```bash
$ git blame src/conky.cc | grep -E 'draw_shades|draw_outline'
b713536d src/conky.cc (Pavel Labath       2010-03-05 14:10:47 +0100  540) static conky::simple_config_setting<bool> draw_shades("draw_shades", true, false);
b713536d src/conky.cc (Pavel Labath       2010-03-05 14:10:47 +0100  541) static conky::simple_config_setting<bool> draw_outline("draw_outline", false, false);
b713536d src/conky.cc (Pavel Labath       2010-03-05 14:10:47 +0100 1957) 		if (draw_shades.get(*state) && !draw_outline.get(*state)) {
b713536d src/conky.cc (Pavel Labath       2010-03-05 14:10:47 +0100 1966) 		if (draw_outline.get(*state)) {
```
Maybe it was before `2010-03-05` or it is something else entirely. Clickable reference: b713536d Side note: I can't git bisect this because older versions does not work, but is consistent across some successfully compiled older versions.... so I can't confirm anything.

If we toggle `outline` and/or `shades` settings here with default config...
```
    draw_outline = true,
    draw_shades = false,
    default_outline_color = 'red',
    default_shade_color = 'violet',
```
... and you'll see that they all worked. The font will slightly blur for me with either setting on and both `true` does not display both colors, only one. I wonder if slightly blurred font is an issue too. It's unbearable.
