### ISSUE TITLE
Feature request: display the kernel number without the suffix

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [brndnmtthws/conky#837]
**Issue**

&nbsp;&nbsp;&nbsp;&nbsp;It would be nice were `${kernel}` to be complemented by a command to display the kernel number _on its own_, i.e. without the 'generic' suffix (or, 'low-latency' or whatever string is displayed for such kernels). I could write a script to do this, but my Conky runs many a script already and since Conky itself already has `${kernel}`, I thought perhaps you could implement something on the lines of `${kernelNum}`.

&nbsp;&nbsp;&nbsp;&nbsp;To be clear: at present, Conky can display:

> 5.1.0-050100-generic

I'd like it to be able to display:

> 5.1.0-050100

**Information**

Conky 1.10.8

**Comment by lasers** [comment]
It looks like `-generic` is part of kernel name so `${kernel}` is correct. There is also `${sysname}`, `${nodename}`, `${machine}`, etc.

My opinion is that you make a script instead because it is trivial and that making `${kernelNum}` does not benefit the users at all. I don't think you even need a script as you might be able to do it inline instead... `${execpi 3600 uname -r | cut -d- -f1}` or so. Maybe unix philosophy and all that.

**Comment by LinuxOnTheDesktop** [comment]
I had not realised one can insert bash into conky like that. Job done. Thank you.
