### ISSUE TITLE
Double monitor - different sizes - gap_y incorrectly

### ISSUE THREAD

**Issue by LeoIannacone** [brndnmtthws/conky#88]
Hi,

I have two monitors, one in vertical with height of 1280, one normal with height of 1024.

When I set conky to show in that monitor, gap_x works as expected, gap_y no.

It seems that gap_y takes care of the first one monitor (height 1024).. so the result is more padding than expected.

Here I set gap_y = 20
![screenshot from 2015-06-18 08 14 16](https://cloud.githubusercontent.com/assets/1774748/8225204/0dff650e-1592-11e5-8dcb-527020bf101f.png)

The problem does not occur only if I run conky from a terminal that's placed in the 1024h.

If move terminal on the vertical one 1280h (where gap_x refers to), everything is right.

**Comment by marcpayne** [comment]
I'm going to link this issue up with #173, since it appears to be related.

**Comment by lasers** [comment]
3 years 2 months passed. Can you determine if you're still having this problem today on `1.10.8` or `1.10.9_pre`? The older versions are not trustworthy. Thank you. Possibly resolved by #173's PR.

**Comment by lasers** [comment]
Hi friends. To start things off, this issue is with an old pre.1.10 config.

I tested this issue with (new) default config on the following layouts:

![2018-08-29-161554_555x446_scrot](https://user-images.githubusercontent.com/852504/44816896-40377880-aba9-11e8-84a1-326c2d000f56.png)




The new default config contains 50+ settings. The important settings are `alignment = 'top_left'`, `gap_x = 5`, and `gap_y = 60`. I added `xinerama_head` on top of this config with either `0` or `1`.

Everything looks fine on my end.

The linked PR above appears to be related and were merged in Dec 4, 2015. That's when this issue should had been closed... roughly 5 months 16 days later. Since that didn't happen, I will be closing this issue now instead... roughly 3 years 3 months later. Cheers! :blush:
