### ISSUE TITLE
[Feature Request] Use lsb_release to optionaly get distribution name on Linux

### ISSUE THREAD

**Issue by SGOrava** [brndnmtthws/conky#939]
**Issue**

Modern distributions include lsb_release or at least /etc/lsb-release file which contains information about given distribution.
https://linux.die.net/man/1/lsb_release

The current implementation can recognize Arch Linux (if file /etc/arch-release) exist and than goes to parse /proc/version which may result in false result.

Best regards

**Comment by Roesjka** [comment]
Debian testing doesn't have /etc/lsb-release. So I did the easy way to get Debian testing
${font DejaVu Sans:bold:size=12}${color0}Debian ${exec cat /etc/debian_version | cut -d "/" -f 1}${font}${color}.
Could use issue.net or os-release
cheers

**Comment by servimo** [comment]
I use this:
${exec lsb_release -r} ${exec lsb_release -c}
To get "Release" and "Codename".

**Comment by Caellian** [comment]
I recently looked into this because I wanted to add distribution to log output so people don't forget to report it in issues. As others have stated, there's no standard/common way of getting that information in distribution agnostic way, otherwise I would've added it at the time (though not the variable immediately).

The most portable way of achieving this I was able to find was:
```
( lsb_release -ds || cat /etc/*release || uname -om ) 2>/dev/null | head -n1
```
<sub><em>NOTE:</em> The above command didn't work for me due to a blank line at the beginning of <code>/etc/*-release</code> file, adding  <code>| grep -v "^$"</code> before piping to `head -n1` fixed it.</sub>

I'm generally against writing code that executes shell commands, and in context of conky it isn't even an improvement since `exec` exists. And given the chain of commands we'd need to run (which might not even work in some cases), it's simpler if you just print the exact information you need in a way that works for distros you use.

If we added support for this feature to conky, its performance would likely be the same as just running `exec`, so I'm closing this as wontfix for now.
