### ISSUE TITLE
Install conky without sudo rights

### ISSUE THREAD

**Issue by mezianem** [brndnmtthws/conky#947]
Everything is in the title :).
I want to install conky on my machine from sources, and apparently lua (`'lua>=5.3;lua5.3;lua-5.3;lua53;lua5.2;lua-5.2;lua52'`) and imlib2(`imlib2;Imlib2`) are missing on my system. I do not have the admin rights on this machine to install them to default location. 
Is there anyway to tell to cmake to search the required libraries on an alternative place ? 
More generally, does anyone have any idea on how one could install the program without root permissions ?

Many thanks

**Comment by SzymonScholz** [comment]
maybe brew/homebrew ?

**Comment by Sih-Nejma** [comment]
:/ unfortunately I don't have these tools

**Comment by simotek** [comment]
It is possible without any changes to config, if you build lua and Imlib2 and install them into your home directory you should end up with .pc files they will probably end up in lib/pkgconfig or lib64/pkgconfig you should then be able to set your PKG_CONFIG_PATH environment variable to also point to the full path to lib64/pkgconfig and cmake should then find and use the lua and Imlib2 in your home directory.

This bug can probably be closed because it shouldn't need changes to conky.
