### ISSUE TITLE
Unicode blocks for console_bar

### ISSUE THREAD

**Issue by m-wells** [brndnmtthws/conky#959]
I would love to use [Unicode block elements](https://en.wikipedia.org/wiki/Block_Elements) with the `console_bar_fill`, `console_bar_unfill`, and `console_graph_ticks` configuration variables.  This would allow me to make good looking conky statuslines.  However, the bars produced by conky do not show the correct glyphs.  The strange part is the glyphs do display properly outside of bars and graphs.

A sample configuration file:
```
conky.config = {
    background = false,
    font = 'DejaVu Sans Mono:size=12',
    out_to_console = true,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = false,
    use_xft = true,
    console_bar_fill = '█',
    console_bar_unfill = '░',
    console_graph_ticks = ' ,▁,▂,▃,▄,▅,▆,▇,█',
}

conky.text = [[
${membar}
console_bar_fill = '█',
console_bar_unfill = '░',
console_graph_ticks = ' ,▁,▂,▃,▄,▅,▆,▇,█',
]]
```
And the output
```
�����
console_bar_fill = '█',
console_bar_unfill = '░',
console_graph_ticks = ' ,▁,▂,▃,▄,▅,▆,▇,█',
```
Am I missing something here?

**Comment by ancientjpeg** [comment]
I'm having a similar issue. Poking around in the source code, I believe this _may_ be due to the progress bar functions in C being written with 8-bit chars in mind. I'm not familiar enough with conky's code to say this definitively however. In the meantime, I think a temporary solution may be to set your console_bar and console_graph characters to readable ASCII characters, and then write a custom Lua script that will parse your bars and graphs in conky.text and replace the ASCII placeholders with the desired unicode characters. However, I would also appreciate if these new conky.config options were capable of accepting and parsing unicode characters.

**Comment by nojhan** [comment]
What would it take to have unicode support in conky? Replace `char` by `wchar_t` everywhere? Use `std::wstring` instead of `char* buffer`? Is the code using C-style allocations because of Lua? How can we help?

**Comment by jdreo** [comment]
I would also like to see this bug fixed (or this feature added?).
