### ISSUE TITLE
"conky -i 5" has no effect (since update to 1.10.0)

### ISSUE THREAD

**Issue by fdietze** [brndnmtthws/conky#97]
```
conky: Invalid value of type 'table' for setting 'total_run_times'. Expected value of type 'number'.
```

**Comment by achilleas-k** [comment]
Same happens for other command line arguments that accept numerical values:
```
$ conky -c ~/.conky/panel.conky -y 100
conky: Invalid value of type 'table' for setting 'gap_y'. Expected value of type 'number'.
```

The result is the conky panel being created at an arbitrary Y location (~60), regardless of specified value. If `gap_y` is specified in the config file, it behaves as expected (assuming no `-y` is specified on the command line).

**Comment by marcpayne** [comment]
I can confirm this. The problem is that `config_setting_base::lua_set` in `setting.cc` seems to misinterpret what is actually on the stack. Here is a short breakdown of what is happening. I should note that I am using Lua 5.3.

Suppose we are processing `total_run_times`. On entry into `lua_set`, the stack looks like this:
```
| ... total_run_times |
```

After `l.getglobal("conky");` we have
```
| ... total_run_times  some_table  conky |
```

By hand tracing through `getglobal`, it seems that `some_table` is `registry[LUA_RIDX_GLOBALS]`. Whether or not this is the intended behavior of `getglobal`, an easy fix is to add `l.replace(-2);` after the call to `getglobal`. Doing so solves the problem for me.

**Comment by marcpayne** [comment]
@fdietze Just doing some housekeeping. This issue has been fixed, so it can be closed now.
