### ISSUE TITLE
Conky no longer plays nicely with root-tail or fvwm

### ISSUE THREAD

**Issue by frankspace** [brndnmtthws/conky#99]
After the 1.10 update, if "own_window = false", Conky prevents root-tail from displaying anything (except briefly in between Conky updates, it appears).  I have experimented with every setting I can think of to no avail.

Conversely, if "own_window = true," Conky can no longer be swallowed and forced to pretend like it's part of the root window, at least in FVWM, and again despite experimenting with everything I can think of.

Previously, under version 1.9, I did have "own_window yes" and had FVWM swallow it into a "button" and it acted like part of the desktop.  Unfortunately, reverting back to 1.9 is the only way I have found to restore this functionality.

**Comment by ahmogit** [comment]
Adding to frankspace's issues with 1.10 under FVWM: 
    * This comment line is treated as a syntax error
        # $Id: .conkyrc,v 3.14 2014/10/25 18:15:29 xxx Exp $
       The reported error is:
           Syntax error (/home/XXX/.conkyrc:2: unexpected symbol near '#') while reading config file. 
           Assuming it's in old syntax and attempting conversion.

    * The app name advertised to X was evidently changed from "Conky" to "conky", thus hosing style settings that had expected the case-sensitive name to apply. Not implying this is a bug, probably intentional, just pointing it out in case others may benefit from it.

**Comment by lasers** [comment]
3 years 1 month passed. Can you determine if you're still having this problem today on `1.10.8` or `1.10.9_pre`? The older versions are not trustworthy. Thank you.

**Comment by lasers** [comment]
Can you try the current master? Thanks.

```bash
git clone https://github.com/brndnmtthws/conky
cd conky
mkdir -p build
cd build
cmake ..
make -j4  # 4 cores to run in parallel
src/conky -c ~/conky.conf # <-- your config goes here
```

**Comment by lasers** [comment]
Hi all. I am checking up on this issue so I'm on `fvwm` right now. I find that there is no `root-tail` on Arch Linux repositories so I can't install this one. The program may be obsolete too.

If I understand you correctly, I don't have this problem right now. I made screenshots too. I didn't touch anything other than `own_window` (bool) and `own_window_type` (normal/desktop) with default config.


![2018-09-07-151733_scrot](https://user-images.githubusercontent.com/852504/45241642-cf801280-b2b2-11e8-88ed-5cf3ffaf9372.png)
![2018-09-07-151725_scrot](https://user-images.githubusercontent.com/852504/45241532-71ebc600-b2b2-11e8-8a67-30cd2c0b40fc.png)
![2018-09-07-151754_scrot](https://user-images.githubusercontent.com/852504/45241533-71ebc600-b2b2-11e8-9fb9-f90c8469990b.png)

This issue is obsolete after 3 years 2 months.

One month later and no response. I think we're done here.

Sorry about the issue and thanks for the report. Keep them coming.
